# Project 2: Build Decision Tree for Attrition Rate Analysis

DV - "Attrition"

IDV - Output of RF Algorithm

In [1]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn import preprocessing

In [4]:
att_train=pd.read_csv("general_data.csv")
att_train.head(5)

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,4.0,Y,12,8,2,9.0,2,6,0,4

In [5]:
att_train.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeID', 'Gender',
       'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'Over18', 'PercentSalaryHike', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

# Random Forest for selecting important features

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
att_train.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeID                  0
Gender                      0
JobLevel                    0
JobRole                     0
MaritalStatus               0
MonthlyIncome               0
NumCompaniesWorked         19
Over18                      0
PercentSalaryHike           0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           9
TrainingTimesLastYear       0
YearsAtCompany              0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

There are null values in Num of Companies Worked and total working years. SO, as they are continous we will replace it by mean.

In [30]:
new_var = np.where(att_train['NumCompaniesWorked'].isnull(),att_train['NumCompaniesWorked'].mean(),att_train['NumCompaniesWorked'])
att_train['NumCompaniesWorked']=new_var
new_var2 = np.where(att_train['TotalWorkingYears'].isnull(),att_train['TotalWorkingYears'].mean(),att_train['TotalWorkingYears'])
att_train['TotalWorkingYears']=new_var
att_train.isnull().sum().sum()

0

In [31]:
objList = att_train.select_dtypes(include = "object").columns
print (objList)

Index([], dtype='object')

In [32]:
#Label Encoding for object to numeric conversion
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in objList:
    att_train[feat] = le.fit_transform(att_train[feat].astype(str))

att_train.head(10)

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,0,2,2,6,2,1,1,1,0,...,1.0,0,11,8,0,1.0,6,1,0,0
1,31,1,1,1,10,1,1,1,2,0,...,0.0,0,23,8,1,0.0,3,5,1,4
2,32,0,1,1,17,4,4,1,3,1,...,1.0,0,15,8,3,1.0,2,5,0,3
3,38,0,0,1,2,5,1,1,4,1,...,3.0,0,11,8,3,3.0,5,8,7,5
4,32,0,2,1,10,1,3,1,5,1,...,4.0,0,12,8,2,4.0,2,6,0,4
5,46,0,2,1,8,3,1,1,6,0,...,3.0,0,13,8,0,3.0,5,7,7,7
6,28,1,2,1,11,2,3,1,7,1,...,2.0,0,20,8,1,2.0,2,0,0,0
7,29,0,2,1,18,3,1,1,8,1,...,2.0,0,22,8,3,2.0,2,0,0,0
8,31,0,2,1,1,3,1,1,9,1,...,0.0,0,21,8,0,0.0,2,9,7,8
9,25,0,0,1,7,4,3,1,10,0,...,1.0,0,13,8,1,1.0,2,6,1,5

In [33]:
rf_model=RandomForestClassifier(n_estimators=1000,max_features=2,oob_score=True)

In [34]:
features=['Age','BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeID', 'Gender',
       'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'Over18', 'PercentSalaryHike', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

In [35]:
rf_model.fit(X=att_train[features],y=att_train['Attrition'])

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=2,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [36]:
print(rf_model.oob_score_)

0.999546485260771

So, the model is 99.95% accurate.

In [38]:
for feature,imp in zip(features,rf_model.feature_importances_):
    print(feature,imp)

Age 0.1012756305872713
BusinessTravel 0.028006092743498075
Department 0.026462545638167526
DistanceFromHome 0.06963990245560811
Education 0.04017390719861266
EducationField 0.041887640723586285
EmployeeCount 0.0
EmployeeID 0.0384569295196118
Gender 0.01768735795986247
JobLevel 0.037117033650208166
JobRole 0.05535031464771784
MaritalStatus 0.039721854064089075
MonthlyIncome 0.09089075910561521
NumCompaniesWorked 0.04637718466433975
Over18 0.0
PercentSalaryHike 0.06470037281926573
StandardHours 0.0
StockOptionLevel 0.03378051899953105
TotalWorkingYears 0.04541496961614397
TrainingTimesLastYear 0.044337915625801534
YearsAtCompany 0.07573083734570164
YearsSinceLastPromotion 0.043309662711307866
YearsWithCurrManager 0.05967856992405987

In this Dataset: Age,DistanceFromHome,MonthlyIncome,PercentSalaryHike,YearsAtCompany Can be considered as imp. features.

In [39]:
imp_features=['Age', 'DistanceFromHome', 'MonthlyIncome','PercentSalaryHike','YearsAtCompany']
rf_model.fit(X=att_train[imp_features],y=att_train['Attrition'])
print(rf_model.oob_score_)

1.0

Thus, now the model is 100% accurate.

# Classification

In [40]:
tree_model = tree.DecisionTreeClassifier(max_depth=8)
features=['Age', 'DistanceFromHome', 'MonthlyIncome','PercentSalaryHike','YearsAtCompany']
tree_model.fit(X=att_train[features],y=att_train['Attrition'])

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=8, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [41]:
with open('att_Dtree.dot','w') as f:
    f=tree.export_graphviz(tree_model,feature_names=features,out_file=f)

Inferences from Classification:

In [42]:
r=tree.export_text(tree_model,feature_names=features)
print(r)

|--- YearsAtCompany <= 1.50
|   |--- Age <= 33.50
|   |   |--- MonthlyIncome <= 112610.00
|   |   |   |--- Age <= 22.50
|   |   |   |   |--- MonthlyIncome <= 23140.00
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- MonthlyIncome >  23140.00
|   |   |   |   |   |--- Age <= 18.50
|   |   |   |   |   |   |--- DistanceFromHome <= 4.00
|   |   |   |   |   |   |   |--- PercentSalaryHike <= 20.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- PercentSalaryHike >  20.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- DistanceFromHome >  4.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- Age >  18.50
|   |   |   |   |   |   |--- MonthlyIncome <= 106255.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- MonthlyIncome >  106255.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- Age >  22.50
|   |   |   |   |--- MonthlyIncome <= 72530.00
|   |   |   |   |   |--- DistanceFromHome <= 2.50
|   |   |   |   |   |   |--- PercentSalaryHike <= 23.50
|   |   |   |   |   |   |   |--- Age <= 27.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- Age >  27.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- PercentSalaryHike >  23.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- DistanceFromHome >  2.50
|   |   |   |   |   |   |--- MonthlyIncome <= 31000.00
|   |   |   |   |   |   |   |--- MonthlyIncome <= 27080.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- MonthlyIncome >  27080.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- MonthlyIncome >  31000.00
|   |   |   |   |   |   |   |--- DistanceFromHome <= 8.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- DistanceFromHome >  8.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- MonthlyIncome >  72530.00
|   |   |   |   |   |--- DistanceFromHome <= 1.50
|   |   |   |   |   |   |--- PercentSalaryHike <= 12.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- PercentSalaryHike >  12.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- DistanceFromHome >  1.50
|   |   |   |   |   |   |--- class: 1
|   |   |--- MonthlyIncome >  112610.00
|   |   |   |--- DistanceFromHome <= 5.00
|   |   |   |   |--- class: 0
|   |   |   |--- DistanceFromHome >  5.00
|   |   |   |   |--- MonthlyIncome <= 161855.00
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- MonthlyIncome >  161855.00
|   |   |   |   |   |--- Age <= 30.50
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- Age >  30.50
|   |   |   |   |   |   |--- class: 1
|   |--- Age >  33.50
|   |   |--- DistanceFromHome <= 2.50
|   |   |   |--- MonthlyIncome <= 24545.00
|   |   |   |   |--- class: 0
|   |   |   |--- MonthlyIncome >  24545.00
|   |   |   |   |--- Age <= 39.50
|   |   |   |   |   |--- Age <= 36.50
|   |   |   |   |   |   |--- PercentSalaryHike <= 12.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- PercentSalaryHike >  12.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 26140.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- MonthlyIncome >  26140.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- Age >  36.50
|   |   |   |   |   |   |--- MonthlyIncome <= 76330.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- MonthlyIncome >  76330.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- Age >  39.50
|   |   |   |   |   |--- PercentSalaryHike <= 16.50
|   |   |   |   |   |   |--- Age <= 44.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 105090.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- MonthlyIncome >  105090.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- Age >  44.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 146145.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- MonthlyIncome >  146145.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- PercentSalaryHike >  16.50
|   |   |   |   |   |   |--- class: 0
|   |   |--- DistanceFromHome >  2.50
|   |   |   |--- Age <= 57.00
|   |   |   |   |--- MonthlyIncome <= 106980.00
|   |   |   |   |   |--- PercentSalaryHike <= 13.50
|   |   |   |   |   |   |--- DistanceFromHome <= 14.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 56325.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- MonthlyIncome >  56325.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- DistanceFromHome >  14.50
|   |   |   |   |   |   |   |--- DistanceFromHome <= 19.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- DistanceFromHome >  19.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- PercentSalaryHike >  13.50
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- MonthlyIncome >  106980.00
|   |   |   |   |   |--- PercentSalaryHike <= 14.50
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- PercentSalaryHike >  14.50
|   |   |   |   |   |   |--- DistanceFromHome <= 5.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- DistanceFromHome >  5.50
|   |   |   |   |   |   |   |--- PercentSalaryHike <= 16.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- PercentSalaryHike >  16.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- Age >  57.00
|   |   |   |   |--- DistanceFromHome <= 7.00
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- DistanceFromHome >  7.00
|   |   |   |   |   |--- DistanceFromHome <= 13.00
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- DistanceFromHome >  13.00
|   |   |   |   |   |   |--- class: 0
|--- YearsAtCompany >  1.50
|   |--- Age <= 33.50
|   |   |--- YearsAtCompany <= 3.50
|   |   |   |--- DistanceFromHome <= 7.50
|   |   |   |   |--- MonthlyIncome <= 73705.00
|   |   |   |   |   |--- MonthlyIncome <= 59150.00
|   |   |   |   |   |   |--- PercentSalaryHike <= 13.50
|   |   |   |   |   |   |   |--- YearsAtCompany <= 2.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- YearsAtCompany >  2.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- PercentSalaryHike >  13.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 48050.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- MonthlyIncome >  48050.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- MonthlyIncome >  59150.00
|   |   |   |   |   |   |--- DistanceFromHome <= 2.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- DistanceFromHome >  2.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- MonthlyIncome >  73705.00
|   |   |   |   |   |--- class: 0
|   |   |   |--- DistanceFromHome >  7.50
|   |   |   |   |--- MonthlyIncome <= 115880.00
|   |   |   |   |   |--- MonthlyIncome <= 34745.00
|   |   |   |   |   |   |--- YearsAtCompany <= 2.50
|   |   |   |   |   |   |   |--- DistanceFromHome <= 19.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- DistanceFromHome >  19.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- YearsAtCompany >  2.50
|   |   |   |   |   |   |   |--- DistanceFromHome <= 20.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- DistanceFromHome >  20.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- MonthlyIncome >  34745.00
|   |   |   |   |   |   |--- PercentSalaryHike <= 13.50
|   |   |   |   |   |   |   |--- Age <= 20.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- Age >  20.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- PercentSalaryHike >  13.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 87460.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- MonthlyIncome >  87460.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- MonthlyIncome >  115880.00
|   |   |   |   |   |--- PercentSalaryHike <= 19.50
|   |   |   |   |   |   |--- MonthlyIncome <= 191730.00
|   |   |   |   |   |   |   |--- PercentSalaryHike <= 16.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- PercentSalaryHike >  16.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- MonthlyIncome >  191730.00
|   |   |   |   |   |   |   |--- MonthlyIncome <= 196390.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- MonthlyIncome >  196390.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- PercentSalaryHike >  19.50
|   |   |   |   |   |   |--- class: 0
|   |   |--- YearsAtCompany >  3.50
|   |   |   |--- DistanceFromHome <= 26.50
|   |   |   |   |--- DistanceFromHome <= 15.50
|   |   |   |   |   |--- PercentSalaryHike <= 11.50
|   |   |   |   |   |   |--- DistanceFromHome <= 14.50
|   |   |   |   |   |   |   |--- YearsAtCompany <= 13.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- YearsAtCompany >  13.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- DistanceFromHome >  14.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- PercentSalaryHike >  11.50
|   |   |   |   |   |   |--- YearsAtCompany <= 4.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 23915.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- MonthlyIncome >  23915.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- YearsAtCompany >  4.50
|   |   |   |   |   |   |   |--- Age <= 23.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- Age >  23.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- DistanceFromHome >  15.50
|   |   |   |   |   |--- MonthlyIncome <= 20570.00
|   |   |   |   |   |   |--- PercentSalaryHike <= 17.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- PercentSalaryHike >  17.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- MonthlyIncome >  20570.00
|   |   |   |   |   |   |--- Age <= 25.50
|   |   |   |   |   |   |   |--- YearsAtCompany <= 5.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- YearsAtCompany >  5.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- Age >  25.50
|   |   |   |   |   |   |   |--- YearsAtCompany <= 9.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- YearsAtCompany >  9.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- DistanceFromHome >  26.50
|   |   |   |   |--- YearsAtCompany <= 7.50
|   |   |   |   |   |--- MonthlyIncome <= 46375.00
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- MonthlyIncome >  46375.00
|   |   |   |   |   |   |--- DistanceFromHome <= 27.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- DistanceFromHome >  27.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- YearsAtCompany >  7.50
|   |   |   |   |   |--- class: 0
|   |--- Age >  33.50
|   |   |--- MonthlyIncome <= 10300.00
|   |   |   |--- class: 1
|   |   |--- MonthlyIncome >  10300.00
|   |   |   |--- YearsAtCompany <= 38.50
|   |   |   |   |--- DistanceFromHome <= 3.50
|   |   |   |   |   |--- PercentSalaryHike <= 18.50
|   |   |   |   |   |   |--- YearsAtCompany <= 16.50
|   |   |   |   |   |   |   |--- Age <= 36.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- Age >  36.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- YearsAtCompany >  16.50
|   |   |   |   |   |   |   |--- Age <= 39.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- Age >  39.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- PercentSalaryHike >  18.50
|   |   |   |   |   |   |--- YearsAtCompany <= 2.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- YearsAtCompany >  2.50
|   |   |   |   |   |   |   |--- Age <= 51.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- Age >  51.50
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- DistanceFromHome >  3.50
|   |   |   |   |   |--- DistanceFromHome <= 24.50
|   |   |   |   |   |   |--- PercentSalaryHike <= 24.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 20060.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- MonthlyIncome >  20060.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- PercentSalaryHike >  24.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 61760.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- MonthlyIncome >  61760.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- DistanceFromHome >  24.50
|   |   |   |   |   |   |--- Age <= 34.50
|   |   |   |   |   |   |   |--- MonthlyIncome <= 39430.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- MonthlyIncome >  39430.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- Age >  34.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- YearsAtCompany >  38.50
|   |   |   |   |--- class: 1

Some of the inferences:
   
1) The employees with YearsAt Compant <=1.5, Age <=22.5 and MonthlyIncome <= 23140.00 : Attrition "NO"

2)The employees with YearsAtCompany <= 1.50, Age <= 18.50, DistanceFromHome <= 4.00 and PercentSalaryHike <= 20.0 : Attrition "Yes" , whereas PercentSalaryHike > 20.0: Attrition "No".

3)The employees with Age <= 33.50, DistanceFromHome <= 7.50, MonthlyIncome <= 59150.00, PercentSalaryHike <= 13.50 and  1.5<YearsAtCompany <= 2.50: Attrition "Yes" 

4)The employees with Age <= 33.50, DistanceFromHome <= 7.50, MonthlyIncome <= 59150.00, PercentSalaryHike <= 13.50 and YearsAtCompany >  2.50: Attrition "No"..etc